language: node_js
dist: xenial
cache: yarn

stages:
  - Static Tests
  - test

node_js:
  - 10
  - 12
  - 14
env:
  - TEST_SUITE=test
  - TEST_SUITE=test:e2e
script: "yarn run $TEST_SUITE"

jobs:
  include:
    - stage: Static Tests
      name: eslint
      script:
        - yarn run lint
    - name: ShellCheck
      script:
        - shellcheck bin/heroku bin/setup
      language: generic
